# mpv.conf
#
# Main configuration file for the mpv media player program.
# See https://mpv.io/ for more information.
#
# jstnsun

ao=alsa,
autocreate-playlist=same
autofit-larger=60%x60%
cursor-autohide=500
cursor-autohide-fs-only=yes
gpu-api=vulkan,auto
hwdec=nvdec,auto
keep-open=yes
osd-bar=no
profile=high-quality,low-latency
screenshot-dir=~/pictures/screenshots/mpv
screenshot-format=png
screenshot-png-compression=0
screenshot-template="%F-%tY%tm%td-%tH%tM%tS"
sub-fix-timing=yes
video-recenter=yes
vo=gpu-next,
volume-max=150

[audio]
profile-cond=p["current-tracks/video/albumart"] or (container_fps or 0) <= 1
script-opts=osc-visibility=always

[not-audio]
profile-cond=not p["current-tracks/video/albumart"] and (container_fps or 0) > 1
fs=yes
script-opts=osc-visibility=auto
